[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:display]
command=/opt/aimless/run-xvfb.sh
autostart=true
autorestart=true
priority=10
redirect_stderr=true
stdout_logfile=/data/logs/display.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1

[program:desktop]
command=/opt/aimless/run-desktop.sh
autostart=true
autorestart=true
priority=20
redirect_stderr=true
stdout_logfile=/data/logs/desktop.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1

[program:vnc]
command=/opt/aimless/run-vnc.sh
autostart=true
autorestart=true
priority=30
depends_on=display
environment=VNC_PASS="%(ENV_VNC_PASS)s"
redirect_stderr=true
stdout_logfile=/data/logs/vnc.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1

[program:novnc]
command=/opt/aimless/run-novnc.sh
autostart=true
autorestart=true
priority=40
depends_on=display
redirect_stderr=true
stdout_logfile=/data/logs/novnc.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1

[program:aimless]
command=/opt/aimless/run-aimless.sh
autostart=true
autorestart=true
priority=50
depends_on=display
redirect_stderr=true
stdout_logfile=/data/logs/aimless.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1